name: Build binary
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    strategy:
      matrix:
        include:
          - os:
              name: ubuntu
              version: latest
            binary: convco
          - os:
              name: ubuntu
              version: latest
            binary: convco
            cross: true
            target: aarch64-unknown-linux-musl
            suffix: -aarch64
          - os:
              name: macos
              version: latest
            binary: convco
          - os:
              name: windows
              version: latest
            binary: convco.exe
    steps:
      - uses: actions/checkout@v4
      - name: install extra dependencies
        if: matrix.os.name == 'ubuntu'
        run: |
          sudo apt install -y musl-tools

      - name: Install stable toolchain
        if: ${{ !matrix.cross }}
        run: |
          rustup toolchain install --profile minimal stable
          rustup target add x86_64-unknown-linux-musl
      - uses: taiki-e/setup-cross-toolchain-action@v1
        if: matrix.cross
        with:
          target: ${{ matrix.target }}
      - uses: taiki-e/install-action@cross
        if: matrix.cross
      - name: Test on ${{ matrix.os.name }}
        run: cargo test

      - name: Build ${{ matrix.os.name }} binary
        run: |
          cargo build --release
          cargo install --root . --path .

      - name: Upload ${{ matrix.os.name }} binary
        uses: actions/upload-artifact@v4
        with:
          name: convco-${{ matrix.os.name }}${{ matrix.suffix }}
          path: bin/${{ matrix.binary }}

      - name: Upload shell completions
        if: ${{ !matrix.cross && matrix.os.name == 'ubuntu' }}
        uses: actions/upload-artifact@v4
        with:
          name: convco-shell-completions
          path: target/completions

      - name: Debian package
        if: matrix.os.name == 'ubuntu'
        run: |
          cargo install cargo-deb
          cargo deb -- --target=${{ matrix.target || 'x86_64-unknown-linux-musl' }}

      - name: Upload Debian package
        if: matrix.os.name == 'ubuntu'
        uses: actions/upload-artifact@v4
        with:
          name: convco-deb${{ matrix.suffix }}
          path: target/debian
